### ISSUE TITLE
openai function calling

### ISSUE THREAD

**Issue by hyusetiawan** [billxbf/ReWOO#11]
the syntax of the prompt is rather unique `#E1` for example, I wonder if this is on purpose? Because it is rather limiting. For example, I want to introduce a tool called `email` that expects a JSON object of {subject: string, body: string, email: string} is there a way to adjust the prompt to accommodate this case? Or would this affect the efficacy of the framework?

This is especially useful if paired with openai function calling that already supports multiple parameters function calls

**Comment by billxbf** [comment]
You are right, `#E1`  is just an ad-hoc implementation for the Planner. If you are looking for a robust system at scale, it's necessary to fine-tune your Planner LLM on special tokens like `<BO#E>` and `<EO#E>`  (like those `<EOS>` tokens in LM pertaining) to mark the beginning and end of #E and Plans. 

Now it's much easier if you are using openai API since they have granted you fine-tuning endpoint https://platform.openai.com/docs/guides/fine-tuning

Note that this repo is just a proof of concept / idea, you don't need to follow anything strictly in this implementation. 

If you are interested in openai function call based agents, checkout my later repo called Gentopia https://gentopia.readthedocs.io/en/latest/quick_start.html#openai-function-agent

>

**Comment by hyusetiawan** [comment]
gotcha, thanks!
I have done some experiments with multi-agent like gentopia but the output is sorely lacking, I was using gpt-3.5-turbo, perhaps using gpt-4 or even the latest gpt-3.5 instruct would be better
