### ISSUE TITLE
Add custom API endpoint 

### ISSUE THREAD

**Issue by yf007** [billxbf/ReWOO#4]
This can be especially helpful for those in China as an example,
or connect external servers that use Gpt-4 for example

**Comment by billxbf** [comment]
I got your point. Since this repo is just an appendant of the experiments in that paper, I try to make it simple and easy-configuring to match all experiments and tables I've run in the paperwork. Adding extra functionality not mentioned in the paper might confuse paper reviewers.

However, you can easily add your custom endpoint here https://github.com/billxbf/ReWOO/blob/c3c877ac99757b45358b63c18f6fd67b2adbc2f3/nodes/LLMNode.py#LL32C38-L32C38

Plus we are working on a new open-source project aiming for applications, where we do support various types of LLM infusions.
