### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by ZionTilley** [billxbf/ReWOO#5]
Running with either:
python run.py --method rewoo --toolset Google LLM --base_lm gpt-3.5-turbo
Or Gradio results in the following error:
`RateLimitError: You exceeded your current quota, please check your plan and billing details.`
1) I have 3 other apps that use the same key and it works
2) I changed the model to use text-davinci-003 AND gpt-3.5-turbo with no change
3) Added logging to verify my key was correctly being read from ./keys/openai.key file and the model was being passed correctly
4) Verified that my quota had not been exceeded

So key is correct, Quota is not exceeded and model declaration is correct.
Is the framework spamming faster than the API endpoint allows?

**Comment by billxbf** [comment]
hmmm pretty wierd since I've never got into that.
When you say Gradio results in the error, do you mean the live demo I provide?
Becuase if so, you are using a temporary key I gave for that demo, which should work...

Another possibility is that the API rates overflows due to your other 3 apps running simultaneously? :thinking:
