### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by jack-wxm** [billxbf/ReWOO#9]
Can you provide a more detailed explanation on how to use the bootstrapping method to sample the correct 2000 Planner instruction data from 4000 samples? Were these data not generated by any tool and only split into steps? How were the final results obtained from these steps? Were they all generated by LLM?
Thank you

**Comment by billxbf** [comment]
Sure, in plain words, the bootstrapping process is:
- Run ReWOO with davinci-003 or gpt-4 to solve 4000 benchmark tasks (in the paper, a mix of HotpotQA and TriviaQA)
- Evaluate those 4000 predictions(completions) and take only the correct ones (~2000).
- Supervised fine-tuning the Planner using the selected samples. Planner Instruction --> Planner Output. (Reasoning Trace)

The SFT'ed Planner is supposed to be more general than SFT in ReAct since no "tool response" (such as Wikipedia search pages) is learned -- only the reasoning trajectory.  That is one of the core benefits of decoupling Reasoning and Observation.

**Comment by jack-wxm** [comment]
When running ReWOO to solve 4000 benchmark tasks, does it ONLY include the Planner stage? Without tools？

**Comment by billxbf** [comment]
No, it's runing both Planner and Solver with tools (since we need the Solver output to decide if the task succeeds or fails.)
